services:
  db:
    image: postgres:16
    container_name: nhl_topscorer_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"
    volumes:
      - nhl_postgres_data:/var/lib/postgresql/data

volumes:
  nhl_postgres_data:
